server.port: 8080
spring.application.name: service-a
eureka:
  client:
    enabled: false
springdoc:
  swagger-ui:
    show-extensions: true
    show-common-extensions: true
  api-docs:
    resolve-extensions-properties: true
---
spring:
  config:
    activate:
      on-profile:
      - eureka
eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true