server.port: 8181
spring.application.name: gateway



spring.cloud.gateway:
  webfilter:
    correlation-id.enabled: true
spring.cloud.gateway.server.webflux:
  globalcors:
    cors-configurations:
      '[/**]':
        allowedOrigins: '*'
        allowedHeaders: '*'
        allowedMethods:
        - GET
        - POST
        - OPTIONS
  routes:
  - id: test-authorization
    uri: http://localhost:8080
    predicates:
    - Path=/test-authorization/sample
    filters:
    - name: Authorization
      args:
        authorities: READ
    - RewritePath=/test-authorization/?(?<segment>.*), /$\{segment}

  - id: test-authorization-token-OK
    uri: http://localhost:8080
    predicates:
    - Path=/test-authorization-token/sample
    filters:
    - name: AuthorizationToken
      args:
        issuers: ''
        client-ids:
        grant-accesses:
        - jsonPath: '$.roles'
          roles: 'READ'
    - RewritePath=/test-authorization-token/?(?<segment>.*), /$\{segment}

  - id: test-authorization-token-KO
    uri: http://localhost:8080
    predicates:
    - Path=/test-authorization-token-ko/sample
    filters:
    - name: AuthorizationToken
      args:
        issuers: 
        client-ids:
        grant-accesses:
        - jsonPath: '$.roles'
          roles: '_UNKNOWN_ROLE_'
    - RewritePath=/test-authorization-token/?(?<segment>.*), /$\{segment}
    
    
spring.r2dbc:
  url: r2dbc:h2:mem:///test_db;MODE=PostgreSQL

spring:
  security:
    oauth2:
      resourceserver:
        granted-authorities-mapping:
          json-path:
          - '$.my-custom-roles'
        multitenant:
        - id: local
          issuer-uri: http://localhost:9090
        jwt:
          issuer-uri: http://localhost:9090

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    gateway:
      access: read-only
  tracing:
    enabled: true
    sampling:
      probability: 1
logging:
  level:
    '[ch.nexsol]': debug
    '[org.springframework]': info
    '[org.springframework.boot]': info
---
spring:
  config:
    activate:
      on-profile:
      - pgsql
  r2dbc:
    url: r2dbc:postgresql://localhost:15432/scg
    username: spring_cloud_gateway
    password: spring_cloud_gateway
spring.sql.init.mode: always 
---
spring:
  config:
    activate:
      on-profile:
      - eureka
eureka:
  client:
    enabled: true
    fetch-registry: true
spring.cloud.gateway.server.webflux:
  discovery:
    locator:
      enabled: true
spring.cloud.gateway.openapi.hub.enabled: true
openapi.gateway.uri: http://localhost:${server.port}