<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ch.nexsol-tech.gateway</groupId>
        <artifactId>spring-cloud-gateway-plugins</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml </relativePath>
    </parent>
    <artifactId>spring-cloud-gateway-plugins-dependencies</artifactId>
    <name>spring-cloud-gateway-plugins-dependencies</name>
    <description>Spring Cloud Gateway's Plugins Dependencies</description>
    <packaging>pom</packaging>

    <dependencyManagement>

        <dependencies>
            <dependency>
                <groupId>ch.nexsol-tech.gateway</groupId>
                <artifactId>spring-cloud-gateway-audit-core</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ch.nexsol-tech.gateway</groupId>
                <artifactId>spring-cloud-gateway-audit-kafka</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ch.nexsol-tech.gateway</groupId>
                <artifactId>spring-cloud-gateway-audit-redis</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ch.nexsol-tech.gateway</groupId>
                <artifactId>spring-cloud-gateway-audit-r2dbc</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ch.nexsol-tech.gateway</groupId>
                <artifactId>spring-cloud-gateway-filters</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ch.nexsol-tech.gateway</groupId>
                <artifactId>spring-cloud-gateway-routes-core</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ch.nexsol-tech.gateway</groupId>
                <artifactId>spring-cloud-gateway-routes-database</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ch.nexsol-tech.gateway</groupId>
                <artifactId>spring-cloud-gateway-routes-files</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ch.nexsol-tech.gateway</groupId>
                <artifactId>spring-cloud-gateway-routes-openapi</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ch.nexsol-tech.gateway</groupId>
                <artifactId>spring-cloud-gateway-oauth2</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ch.nexsol-tech.gateway</groupId>
                <artifactId>spring-cloud-gateway-hub-openapi</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>

    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>${flatten-maven-plugin.version}</version>
                <inherited>false</inherited>
                <executions>
                    <execution>
                        <!-- Flatten and simplify our own POM for install/deploy -->
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                        <configuration>
                            <updatePomFile>true</updatePomFile>
                            <flattenMode>bom</flattenMode>
                            <pomElements>
                                <properties>remove</properties>
                                <distributionManagement>remove</distributionManagement>
                                <dependencyManagement>keep</dependencyManagement>
                                <repositories>remove</repositories>
                                <issueManagement>remove</issueManagement>
                            </pomElements>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>


</project>
