/*
 * Copyright 2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ch.nexsol.gateway.routes.openapi.autoconfigure;

import ch.nexsol.gateway.routes.openapi.OpenApiRouteDefinitionLocator;
import org.junit.jupiter.api.Test;

import org.springframework.boot.autoconfigure.AutoConfigurations;
import org.springframework.boot.test.context.runner.ApplicationContextRunner;
import org.springframework.cloud.gateway.route.RouteDefinition;
import org.springframework.core.io.ClassPathResource;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Auto-configuration tests wiring {@link RoutesOpenapiAutoConfiguration} end-to-end and
 * verifying the routes generated by the lifecycle from a local OpenAPI document.
 */
class RoutesOpenapiAutoConfigurationTests {

	private final ApplicationContextRunner runner = new ApplicationContextRunner()
		.withConfiguration(AutoConfigurations.of(RoutesOpenapiAutoConfiguration.class));

	@Test
	void locatorIsAbsentWhenDisabled() {
		this.runner.run((context) -> assertThat(context).doesNotHaveBean(OpenApiRouteDefinitionLocator.class));
	}

	@Test
	void locatorGeneratesRoutesWhenEnabled() throws Exception {
		String specPath = new ClassPathResource("openapi/petstore.yaml").getFile().getAbsolutePath();

		this.runner
			.withPropertyValues("spring.cloud.gateway.server.webflux.routes-openapi.enabled=true",
					"spring.cloud.gateway.server.webflux.routes-openapi.sources[0].id=petstore",
					"spring.cloud.gateway.server.webflux.routes-openapi.sources[0].uri=https://backend.example.org",
					"spring.cloud.gateway.server.webflux.routes-openapi.sources[0].spec-url=" + specPath,
					"spring.cloud.gateway.server.webflux.routes-openapi.sources[0].mode=AGGREGATED")
			.run((context) -> {
				assertThat(context).hasSingleBean(OpenApiRouteDefinitionLocator.class);
				OpenApiRouteDefinitionLocator locator = context.getBean(OpenApiRouteDefinitionLocator.class);
				locator.refresh().block();
				assertThat(locator.getRouteDefinitions().map(RouteDefinition::getId).collectList().block())
					.containsExactly("petstore");
			});
	}

}
